// One-shot: download Inter + JetBrains Mono (variable) and emit src/fonts.css
// with base64 @font-face data URIs so the video is fully self-contained for capture.
//   node scripts/get-fonts.mjs
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { pipeline } from "node:stream/promises";
import { Readable } from "node:stream";
import path from "node:path";

const OUT = path.resolve("src/fonts.css");

// Latin (normal) variable subsets from @fontsource-variable — small, fully offline.
const FACES = [
  { name: "Inter", weight: "100 900", file: "node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2", subset: "latin" },
  { name: "JetBrains Mono", weight: "100 800", file: "node_modules/@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2", subset: "latin" },
];

let css = `/* Self-hosted brand faces (Inter + JetBrains Mono), Latin variable subsets.\n   Generated by scripts/get-fonts.mjs from @fontsource-variable — do not edit by hand. */\n`;
for (const f of FACES) {
  const buf = readFileSync(f.file);
  console.log("inlining", f.name, `${(buf.length / 1024).toFixed(0)} KB`);
  const b64 = buf.toString("base64");
  css += `@font-face {\n  font-family: "${f.name}";\n  font-style: normal;\n  font-weight: ${f.weight};\n  font-display: swap;\n  src: url(data:font/woff2;base64,${b64}) format("woff2");\n  unicode-range: U+0000-00FF, U+2000-206F;\n}\n\n`;
}
writeFileSync(OUT, css);
console.log("wrote", OUT, `${(readFileSync(OUT).length / 1024).toFixed(0)} KB`);
